In [8]:
import pandas as pd

In [9]:
df = pd.DataFrame(
   {"a" : [4, 5, 6], 
   "b" : [7, 8, 9], 
   "c" : [10, 11, 12]},
   index = [1, 2, 3])

In [10]:
df

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [11]:
df.loc[3, "a"]

np.int64(6)

In [12]:
# 특정 행과 컬럼 추출(여러 개일 경우 리스트로)
df.loc[[1, 2], ["a", "b"]]

   a  b
1  4  7
2  5  8

In [13]:
df = pd.DataFrame(
     [[4, 7, 10],
      [5, 8, 11],
      [6, 9, 12]], 
     index=[1, 2, 3], 
     columns=['a', 'b', 'c'])

df

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [ ]:
# 튜플 형태의 데이터로 이중 인덱스 생성
# np.nan -> Numpy(np) 라이브러리에 있는 nan 값을 사용하겠다

import numpy as np
df = pd.DataFrame(
    {"a" : [4 ,5, 6, 6, np.nan], 
    "b" : [7, 8, np.nan, 9, 9], 
    "c" : [10, 11, 12, np.nan, 12]},    
index = pd.MultiIndex.from_tuples(
    [('d', 1), ('d', 2),('e', 2),('e', 3),('e', 4)],
    names=['n', 'v']))

df

       a    b     c
n v
d 1  4.0  7.0  10.0
  2  5.0  8.0  11.0
e 2  6.0  NaN  12.0
  3  6.0  9.0   NaN
  4  NaN  9.0  12.0

In [15]:
# 비교 연산자로 열의 값 비교하기(1)
df[df.b > 7]

       a    b     c
n v
d 2  5.0  8.0  11.0
e 3  6.0  9.0   NaN
  4  NaN  9.0  12.0

In [16]:
# 비교 연산자로 열의 값 비교하기(2)
df[df['c'] > 10]

       a    b     c
n v
d 2  5.0  8.0  11.0
e 2  6.0  NaN  12.0
  4  NaN  9.0  12.0

In [17]:
df

       a    b     c
n v
d 1  4.0  7.0  10.0
  2  5.0  8.0  11.0
e 2  6.0  NaN  12.0
  3  6.0  9.0   NaN
  4  NaN  9.0  12.0

In [18]:
# 중복된 행 제거
# keep='last' -> 중복된 데이터가 발견되었을 때
# 가장 마지막에 나온 데이터만 남기고 다 지우기
df = df.drop_duplicates(keep='last')
df

       a    b     c
n v
d 1  4.0  7.0  10.0
  2  5.0  8.0  11.0
e 2  6.0  NaN  12.0
  3  6.0  9.0   NaN
  4  NaN  9.0  12.0

In [19]:
df["a"] != 7

n  v
d  1    True
   2    True
e  2    True
   3    True
   4    True
Name: a, dtype: bool

In [20]:
# 'b'열의 값이 7이 아닌 행들만 추출(7이 포함된 행은 제외)
df[df["b"] != 7]

       a    b     c
n v
d 2  5.0  8.0  11.0
e 2  6.0  NaN  12.0
  3  6.0  9.0   NaN
  4  NaN  9.0  12.0

In [21]:
# 'a'열에 5와 6이 있는가?
df.a.isin([5, 6])

n  v
d  1    False
   2     True
e  2     True
   3     True
   4    False
Name: a, dtype: bool

In [ ]:
pd.isnull(df)

         a      b      c
n v
d 1  False  False  False
  2  False  False  False
e 2  False   True  False
  3  False  False   True
  4   True  False  False

In [26]:
df['a'].isnull().sum()

np.int64(1)

In [32]:
df.b.notnull().sum()

np.int64(4)

In [31]:
df.notnull()

         a      b      c
n v
d 1   True   True   True
  2   True   True   True
e 2   True  False   True
  3   True   True  False
  4  False   True   True

* 판다스 연산자: &, |, ~, ^, df.any(), df.all()
* 파이썬 연산자: and, or, not, xor, any, all

In [33]:
~df.notnull()

         a      b      c
n v
d 1  False  False  False
  2  False  False  False
e 2  False   True  False
  3  False  False   True
  4   True  False  False

In [43]:
df[(df.b == 7) | (df.a == 5)]

       a    b     c
n v
d 1  4.0  7.0  10.0
  2  5.0  8.0  11.0