In [3]:
import pandas as pd

In [ ]:
df = pd.DataFrame(
   {"a" : [4, 5, 6], 
   "b" : [7, 8, 9], 
   "c" : [10, 11, 12]},
   index = [1, 2, 3])

In [5]:
df

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [6]:
df.loc[3, "a"]

np.int64(6)

In [7]:
# 특정 행과 컬럼 추출(여러 개일 경우 리스트로)
df.loc[[1, 2], ["a", "b"]]

   a  b
1  4  7
2  5  8

In [10]:
df = pd.DataFrame(
     [[4, 7, 10],
      [5, 8, 11],
      [6, 9, 12]], 
     index=[1, 2, 3], 
     columns=['a', 'b', 'c'])

df

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [41]:
# 튜플 형태의 데이터로 이중 인덱스 생성
df = pd.DataFrame(
    {"a" : [4 ,5, 6, 6], 
    "b" : [7, 8, 9, 9], 
    "c" : [10, 11, 12, 12]},    
index = pd.MultiIndex.from_tuples(
    [('d', 1), ('d', 2),('e', 2),('e', 3)],
    names=['n', 'v']))

df

     a  b   c
n v
d 1  4  7  10
  2  5  8  11
e 2  6  9  12
  3  6  9  12

In [31]:
# 비교 연산자로 열의 값 비교하기(1)
df[df.b > 7]

     a  b   c
n v
d 2  5  8  11
e 2  6  9  12
  3  6  9  12

In [32]:
# 비교 연산자로 열의 값 비교하기(2)
df[df['c'] > 10]

     a  b   c
n v
d 2  5  8  11
e 2  6  9  12
  3  6  9  12

In [38]:
df

     a  b   c
n v
d 1  4  7  10
  2  5  8  11
e 2  6  9  12

In [ ]:
# 중복된 행 제거
# keep='last' -> 중복된 데이터가 발견되었을 때
# 가장 마지막에 나온 데이터만 남기고 다 지우기
df = df.drop_duplicates(keep='last')
df

     a  b   c
n v
d 1  4  7  10
  2  5  8  11
e 3  6  9  12

In [46]:
df["a"] != 7

n  v
d  1    True
   2    True
e  3    True
Name: a, dtype: bool

In [55]:
# 'b'열의 값이 7이 아닌 행들만 추출(7이 포함된 행은 제외)
df[df["b"] != 7]

     a  b   c
n v
d 2  5  8  11
e 3  6  9  12

In [ ]:
# 'a'열에 5와 6이 있는가?
df.a.isin([5, 6])

n  v
d  1    False
   2     True
e  3    False
Name: a, dtype: bool