In [53]:
import pandas as pd
import seaborn as sns
import numpy as np

In [54]:
# Seaborn 라이브러리에서 iris 데이터 가져오기
df = sns.load_dataset('iris')
df.shape

(150, 5)

In [55]:
df.head(2)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa

In [56]:
df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [57]:
# df의 행 개수 구하기(1)
len(df)

150

In [58]:
# df의 행 개수 구하기(2)
# df.shape[1] -> df의 열 개수 구하기
df.shape[0]

150

In [59]:
# 'species'열의 고유한 값의 개수 구하기(중복제외)
# Number of Unique
df['species'].nunique()

3

* .nunique(): 종류가 몇 개인지 개수만 알려줌(숫자 형태로 출력)
* .unique(): 종류의 이름이 무엇인지 목록을 보여줌(리스트 형태로 출력)
* .value_counts(): 각 종류별로 데이터가 몇 개씩 있는지 세어줌(표 형태로 출력)

In [60]:
# df의 통계수치를 출력(디폴트는 숫자 타입만 출력)
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [61]:
# df의 숫자, 객체 타입 등 전체 통계수치를 출력
df.describe(include='all')

        sepal_length  sepal_width  petal_length  petal_width species
count     150.000000   150.000000    150.000000   150.000000     150
unique           NaN          NaN           NaN          NaN       3
top              NaN          NaN           NaN          NaN  setosa
freq             NaN          NaN           NaN          NaN      50
mean        5.843333     3.057333      3.758000     1.199333     NaN
std         0.828066     0.435866      1.765298     0.762238     NaN
min         4.300000     2.000000      1.000000     0.100000     NaN
25%         5.100000     2.800000      1.600000     0.300000     NaN
50%         5.800000     3.000000      4.350000     1.300000     NaN
75%         6.400000     3.300000      5.100000     1.800000     NaN
max         7.900000     4.400000      6.900000     2.500000     NaN

In [62]:
# df의 객체 타입의 통계수치만 출력
df.describe(include=[object])

C:\Users\User\AppData\Local\Temp\ipykernel_9928\3723483616.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include=[object])

       species
count      150
unique       3
top     setosa
freq        50

```
sum()
Sum values of each object.
count()
Count non-NA/null values of each object.
median(): 중간값
Median value of each object.
quantile([0.25,0.75]): 특정위치(백분위)에 있는 값
Quantiles of each object.
apply(function)
Apply function to each object.
min()
Minimum value in each object.
max()
Maximum value in each object.
mean(): 평균값
Mean value of each object.
var(): 분산(해당 데이터가 평균으로부터 얼마나 멀리 떨어져 있는지 계산한 값)
Variance of each object.
std(): 표준편차(분산에 루트를 씌운 값)
Standard deviation of each object.
```

In [63]:
df['petal_width'].sum()

np.float64(179.90000000000003)

In [64]:
df['petal_width'].count()

np.int64(150)

In [65]:
df['petal_width'].median()

np.float64(1.3)

In [66]:
df['petal_width'].mean()

np.float64(1.1993333333333336)

In [67]:
df['petal_width'].quantile([0.25, 0.75])

0.25    0.3
0.75    1.8
Name: petal_width, dtype: float64

In [68]:
df.min()

sepal_length       4.3
sepal_width        2.0
petal_length       1.0
petal_width        0.1
species         setosa
dtype: object

In [69]:
df.max()

sepal_length          7.9
sepal_width           4.4
petal_length          6.9
petal_width           2.5
species         virginica
dtype: object

In [71]:
df['petal_width'].var()

np.float64(0.5810062639821029)

In [74]:
df['petal_width'].std()

np.float64(0.7622376689603465)

In [72]:
df['petal_width'].count()

np.int64(150)

### apply(function)

In [97]:
def smp(x):
    # 뒤에서 3번째까지의 문자를 가져오는 함수
    x = x[-3:] 
    return x

In [82]:
# 각 열에서 인덱스가 1인 데이터들만 추출
df.apply(lambda x : x[1])

sepal_length       4.9
sepal_width        3.0
petal_length       1.4
petal_width        0.2
species         setosa
dtype: object

In [96]:
# 'species'열에서 3번째 문자까지만 가져와서 출력
# df의 새로운 열을 생성해서 담기
df['species_3'] = df['species'].apply(lambda x : x[:3])

In [98]:
df['species-3'] = df['species'].apply(smp)

In [99]:
df

,sepal_length,sepal_width,petal_length,petal_width,species,species_3,species-3
0,5.1,3.5,1.4,0.2,setosa,set,osa
1,4.9,3.0,1.4,0.2,setosa,set,osa
2,4.7,3.2,1.3,0.2,setosa,set,osa
3,4.6,3.1,1.5,0.2,setosa,set,osa
4,5.0,3.6,1.4,0.2,setosa,set,osa
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,vir,ica
146,6.3,2.5,5.0,1.9,virginica,vir,ica
147,6.5,3.0,5.2,2.0,virginica,vir,ica
148,6.2,3.4,5.4,2.3,virginica,vir,ica
149,5.9,3.0,5.1,1.8,virginica,vir,ica