In [8]:
import pandas as pd
import numpy as np

In [13]:
df = pd.DataFrame([[np.nan, 2, np.nan, 0],
                   [3, 4, np.nan, 1],
                   [np.nan, np.nan, np.nan, 5]],
                   columns=list('ABCD'))

df

     A    B   C  D
0  NaN  2.0 NaN  0
1  3.0  4.0 NaN  1
2  NaN  NaN NaN  5

In [15]:
# 데이터 전부 삭제(NA 결측치 drop 버리다)
df.dropna()

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [ ]:
# axis가 0일 때는 행을, 1일 때는 열을 기준으로 검사
# how='all' -> 데이터 값이 전부 NaN일 때만 해당 열 전체 drop
# how='any'(기본값) -> 데이터 값이 하나라도 NaN일 때 해당 열 전체 drop
df.dropna(axis=1, how='all')

     A    B  D
0  NaN  2.0  0
1  3.0  4.0  1
2  NaN  NaN  5

In [21]:
df.dropna(axis=0)

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [ ]:
# NaN인 값을 지정한 값으로 채워주기
values = {'A': 0, 'B': 1, 'C': 2, 'D': 3}
df.fillna(value=values)

     A    B    C  D
0  0.0  2.0  2.0  0
1  3.0  4.0  2.0  1
2  0.0  1.0  2.0  5

In [ ]:
# 'D'열의 중간값을 fill_na_value 변수에 저장
fill_na_value = df['D'].median()

In [32]:
# NaN인 값을 fill_na_value 값으로 채워주기
df.fillna(value=fill_na_value)

     A    B    C  D
0  1.0  2.0  1.0  0
1  3.0  4.0  1.0  1
2  1.0  1.0  1.0  5

In [34]:
# 각 컬럼의 null 값 개수 구하기
df.isnull().sum()

A    2
B    1
C    3
D    0
dtype: int64

In [ ]:
# 각 컬럼에서 null이 아닌 값 개수 구하기
df.notnull().sum()

A    1
B    2
C    0
D    3
dtype: int64