In [2]:
import pandas as pd
import numpy as np

In [3]:
# np.random.randn(10) -> 정규분포를 따르는 10개의 숫자를 1차원 배열로 생성
df = pd.DataFrame({'A': range(1,11),
                   'B': np.random.randn(10)})
df

    A         B
0   1  0.651091
1   2 -0.919489
2   3  1.242132
3   4 -0.316774
4   5 -0.460708
5   6 -0.472730
6   7 -0.240104
7   8  0.296243
8   9 -0.544186
9  10  1.383591

In [4]:
# assign(): 기존 데이터프레임을 수정하지 않고, 새로운 컬럼을 붙여 새로운 데이터프레임 반환하는 함수
# 'ln_A'라는 이름의 새로운 컬럼 생성하기
# 'A'컬럼의 log 연산 수행해서 ln_A 컬럼에 저장
df.assign(ln_A = lambda x : np.log(x.A)).head()

   A         B      ln_A
0  1  0.651091  0.000000
1  2 -0.919489  0.693147
2  3  1.242132  1.098612
3  4 -0.316774  1.386294
4  5 -0.460708  1.609438

### apply와 assign의 차이?

* apply: 행이나 열을 따라 사용자가 정의한 함수를 반복 적용할 때 사용
1. 기존 열의 값을 수정하거나, 여러ㅓ 열의 값을 조합해 하나의 결과를 낼 때 유용
2. 복잡한 조건문이나 함수를 모든 데이터에 일일이 적용할 때 유용

* assign: 기존 데이터프레임을 건드리지 않고, 새로운 열이 추가된 새로운 데이터프레임을 반환할 때 사용
1. 새로운 열을 생성하거나 기존 열을 덮어씌우는 '구조적 작업'에 최적화
2. 메서드 체이닝(원본 데이터 수정 X, 여러 명령을 한 줄로 이어서 쓸 때 유용)

In [5]:
# 위의 방식보다 이 방식이 더 표준
df["ln_A"] = np.log(df.A)
df

    A         B      ln_A
0   1  0.651091  0.000000
1   2 -0.919489  0.693147
2   3  1.242132  1.098612
3   4 -0.316774  1.386294
4   5 -0.460708  1.609438
5   6 -0.472730  1.791759
6   7 -0.240104  1.945910
7   8  0.296243  2.079442
8   9 -0.544186  2.197225
9  10  1.383591  2.302585

In [6]:
# qcut(): 동일한 개수(빈도)를 가진 구간으로 나눌 때 사용
# qcut(컬럼, 나눌 구간의 수, 구간의 이름)
pd.qcut(df.A, 3, labels=["good", "medium", "bad"])

0      good
1      good
2      good
3      good
4    medium
5    medium
6    medium
7       bad
8       bad
9       bad
Name: A, dtype: category
Categories (3, str): ['good' < 'medium' < 'bad']

In [ ]:
# 열을 기준으로 최댓값
df.max(axis=1)

0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     6.0
6     7.0
7     8.0
8     9.0
9    10.0
dtype: float64

In [9]:
df

    A         B      ln_A
0   1  0.651091  0.000000
1   2 -0.919489  0.693147
2   3  1.242132  1.098612
3   4 -0.316774  1.386294
4   5 -0.460708  1.609438
5   6 -0.472730  1.791759
6   7 -0.240104  1.945910
7   8  0.296243  2.079442
8   9 -0.544186  2.197225
9  10  1.383591  2.302585

In [ ]:
# 행을 기준으로 최솟값
df.min(axis=0)

A       1.000000
B      -0.919489
ln_A    0.000000
dtype: float64

In [11]:
# -2보다 작은 값을 모두 -2로 변경(하한선)
# 5보다 큰 값을 모두 5로 변경(상한선)
# -2 ~ 5 사이의 값: 원래 값을 그대로 유지
df["A"].clip(lower=-2, upper=5)

0    1
1    2
2    3
3    4
4    5
5    5
6    5
7    5
8    5
9    5
Name: A, dtype: int64

In [12]:
df["B"].clip(lower=1, upper=3)

0    1.000000
1    1.000000
2    1.242132
3    1.000000
4    1.000000
5    1.000000
6    1.000000
7    1.000000
8    1.000000
9    1.383591
Name: B, dtype: float64

In [ ]:
# 절대값 씌워주기
# df.abs와 df.abs()의 차이
# ()의 유무는 '명령을 지금 실행할 것인가?'와 '기능 그 자체를 가리킬 것인가?'의 차이
# df.abs: 메서드 참조 / df.abs(): 메서드 실행
df.abs()

    A         B      ln_A
0   1  0.651091  0.000000
1   2  0.919489  0.693147
2   3  1.242132  1.098612
3   4  0.316774  1.386294
4   5  0.460708  1.609438
5   6  0.472730  1.791759
6   7  0.240104  1.945910
7   8  0.296243  2.079442
8   9  0.544186  2.197225
9  10  1.383591  2.302585

In [19]:
df["B"].abs()

0    0.651091
1    0.919489
2    1.242132
3    0.316774
4    0.460708
5    0.472730
6    0.240104
7    0.296243
8    0.544186
9    1.383591
Name: B, dtype: float64