In [5]:
import pandas as pd

In [6]:
adf = pd.DataFrame({"x1": ["A", "B", "C"],
              "x2": [1, 2, 3]})

adf

  x1  x2
0  A   1
1  B   2
2  C   3

In [7]:
bdf = pd.DataFrame({"x1": ["A", "B", "D"],
                    "x3": ["T", "F", "T"]})

bdf

  x1 x3
0  A  T
1  B  F
2  D  T

In [8]:
# how='left': adf(왼쪽)의 모든 행을 유지
# adf의 'C'는 bdf에 짝이 없으므로, bdf에서 가져올 'x3' 값은 NaN이 된다.
# on='x1': 컬럼 'x1'의 값을 기준으로 짝을 맞춘다
pd.merge(adf, bdf, how='left', on='x1')

  x1  x2   x3
0  A   1    T
1  B   2    F
2  C   3  NaN

In [9]:
pd.merge(adf, bdf, how='right', on='x1')

  x1   x2 x3
0  A  1.0  T
1  B  2.0  F
2  D  NaN  T

In [10]:
# how='inner': 'on'으로 지정한 컬럼(x1)의 값이 두 데이터프레임 모두에 존재하는 행만 합침
pd.merge(adf, bdf, how='inner', on='x1')

  x1  x2 x3
0  A   1  T
1  B   2  F

In [11]:
# how='outer': 모든 값을 합침
pd.merge(adf, bdf, how='outer', on='x1')

  x1   x2   x3
0  A  1.0    T
1  B  2.0    F
2  C  3.0  NaN
3  D  NaN    T

In [12]:
adf.x1.isin(bdf.x1)

0     True
1     True
2    False
Name: x1, dtype: bool

In [13]:
adf[adf.x1.isin(bdf.x1)]

  x1  x2
0  A   1
1  B   2

In [14]:
adf[~adf.x1.isin(bdf.x1)]

  x1  x2
2  C   3

In [15]:
ydf = pd.DataFrame({"x1": ["A", "B", "C"],
                    "x2": [1, 2, 3]})

ydf

  x1  x2
0  A   1
1  B   2
2  C   3

In [16]:
zdf = pd.DataFrame({"x1": ["B", "C", "D"],
                    "x2": [2, 3, 4]})

zdf

  x1  x2
0  B   2
1  C   3
2  D   4

In [17]:
pd.merge(ydf, zdf, how='outer')

  x1  x2
0  A   1
1  B   2
2  C   3
3  D   4

In [18]:
# indicator=True: 차집합을 구하기 위해 사용(또는 데이터 검증)
pd.merge(ydf, zdf, how='outer', indicator=True)

  x1  x2      _merge
0  A   1   left_only
1  B   2        both
2  C   3        both
3  D   4  right_only

In [ ]:
# query(): _merge 컬럼값이 'left_only'인 행만 추출
# drop(): 필터링에 사용했던 임시 컬럼('_merge')을 결과에서 삭제
pd.merge(ydf, zdf, how='outer', indicator=True).query(
    '_merge == "left_only"'
).drop(columns=['_merge'])

  x1  x2
0  A   1

### concat과 merge의 차이

* concat: 주로 데이터프레임을 단순히 이어 붙일 때 사용(기본값은 axis=0)
- 데이터의 내용보다는 index나 컬럼명이 같은지를 보고 그대로 이어 붙임
- ex. 형태가 같은 여러 개의 데이터를 하나로 통합할 때
* merge: 두 데이터프레임의 공통된 키(key)값을 기준으로 데이터를 병합(SQL의 join과 유사)
- 두 테이블에서 공통된 열(key)을 찾아 가로로 이어 붙임
- merge할 때 무조건 공통된 컬럼명을 찾아서는 안됨(컬럼명이 달라도 병합가능)